[package]
name = "sqlx-examples"
version = "0.1.0"
authors = ["Mendelt Siebenga <msiebenga@gmail.com>"]
edition = "2018"

[dependencies]
sqlx = { version="0.4.0-beta.1", features=["postgres"] }
async-std = { version="1.6.3", features=["attributes"] }

[dev-dependencies]
serde_json = "1.0"
